In [1]:
#Esercizio 1

import numpy as np

a = np.array([2,3,5,7,11,13,17,19])

print(a[a>10])
print(a[a%2==0])

[11 13 17 19]
[2]


In [2]:
#Esercizio 2

import numpy as np

a = np.random.randint(0 ,11, size=(5,5))
print(a)

b = a[1::2,::]
print(b)

c = a[2,::]
print(c)

a_diviso_c = a/c
print(a_diviso_c)



[[ 3  6  9  3  6]
 [ 9  7  7  4  2]
 [ 8  8 10  3  6]
 [ 4  8  8  4  2]
 [ 7  6 10  5  5]]
[[9 7 7 4 2]
 [4 8 8 4 2]]
[ 8  8 10  3  6]
[[0.375      0.75       0.9        1.         1.        ]
 [1.125      0.875      0.7        1.33333333 0.33333333]
 [1.         1.         1.         1.         1.        ]
 [0.5        1.         0.8        1.33333333 0.33333333]
 [0.875      0.75       1.         1.66666667 0.83333333]]


In [9]:
#Esercizio 3

import numpy as np

a = np.random.random(size=(10,3))
print(a)

differenze = np.abs(a - 0.5)
indici = np.argmin(differenze,axis=1)
valori_piu_vicini = a[np.arange(10),indici]

for i in range(10):
    print(f"Riga {i}: {a[i]}")
    print(f"L'elemento più vicino a 0.5 della riga è: {valori_piu_vicini[i]}")


[[0.44072417 0.28183574 0.96096934]
 [0.06124377 0.80460132 0.44327106]
 [0.7709078  0.85187804 0.75029834]
 [0.05095323 0.46603386 0.45074261]
 [0.81255909 0.0539115  0.2894441 ]
 [0.82068092 0.56686799 0.60214839]
 [0.57880294 0.24746273 0.22362204]
 [0.21001682 0.86898285 0.75421751]
 [0.96935679 0.30424658 0.89983867]
 [0.7751969  0.33620861 0.16189092]]
Riga 0: [0.44072417 0.28183574 0.96096934]
L'elemento più vicino a 0.5 della riga è: 0.4407241666735632
Riga 1: [0.06124377 0.80460132 0.44327106]
L'elemento più vicino a 0.5 della riga è: 0.4432710613320595
Riga 2: [0.7709078  0.85187804 0.75029834]
L'elemento più vicino a 0.5 della riga è: 0.7502983429289855
Riga 3: [0.05095323 0.46603386 0.45074261]
L'elemento più vicino a 0.5 della riga è: 0.4660338610985989
Riga 4: [0.81255909 0.0539115  0.2894441 ]
L'elemento più vicino a 0.5 della riga è: 0.2894440996659635
Riga 5: [0.82068092 0.56686799 0.60214839]
L'elemento più vicino a 0.5 della riga è: 0.5668679866815692
Riga 6: [0.5788

In [16]:
#Esercizio 4

import numpy as np

frequenza_cardiaca = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 
                               164, 163, 162, 100, 90, 97, 72, 60, 70])

frequenza_minima = np.amin(frequenza_cardiaca)
print(frequenza_minima)

frequenza_massima = np.amax(frequenza_cardiaca)
print(frequenza_massima)

attivita_fisica = np.where(frequenza_cardiaca > 120, True, False)
print(attivita_fisica)

contatore = 0

for frequenza in attivita_fisica:
    if frequenza == True:
        contatore = contatore + 1

print(contatore/len(frequenza_cardiaca))

60
164
[False False False False  True  True  True  True  True  True  True  True
  True  True  True False False False False False False]
0.5238095238095238


In [24]:
#Esercizio 5

a = np.array([50000,105250,55000,89000])

a_aumento_ceo = np.where(a == 105250, a * 1.15, a)
print(a_aumento_ceo)

a_aumento_1 = np.where(a_aumento_ceo == 50000, a_aumento_ceo*1.2, a_aumento_ceo)
print(a_aumento_1)

a_aumento_2 = np.where( a_aumento_1 == a, a*1.1, a_aumento_1)
print(a_aumento_2)

totale_no_aumenti = np.sum(a)
totale_aumenti = np.sum(a_aumento_2)

print(totale_aumenti - totale_no_aumenti)

[ 50000.  121037.5  55000.   89000. ]
[ 60000.  121037.5  55000.   89000. ]
[ 60000.  121037.5  60500.   97900. ]
40187.5


In [33]:
#Esercizio 6

import numpy as np

survey_matrix = np.array([ [25, 40000, 10], [32, 52000, 12], [40, 63000, 14], [29, 47000, 11], 
                          [35, 58000, 13] ])
survey_matrix_12_anni= survey_matrix[survey_matrix[:,2] >= 12]
print("I dipendenti con almeno 12 anni di esperienza sono:\n", survey_matrix_12_anni)

survey_matrix_redditi = survey_matrix_12_anni[:,1]
print("I redditi dei dipendenti con almeno 12 anni di esperienza sono:\n", survey_matrix_redditi)

media_redditi = np.mean(survey_matrix_redditi)
print("La media dei redditi dei dipendenti con almeno 12 anni di esperienza è:", media_redditi,"dollari.")


I dipendenti con almeno 12 anni di esperienza sono:
 [[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]]
I redditi dei dipendenti con almeno 12 anni di esperienza sono:
 [52000 63000 58000]
La media dei redditi dei dipendenti con almeno 12 anni di esperienza è: 57666.666666666664 dollari.
